import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://beta-app.sigparser.com/');
  await page.getByRole('button', { name: 'Envelope Login with Email' }).click();
  await page.getByPlaceholder('Enter your email address').click();
  await page.getByPlaceholder('Enter your email address').fill('test+stafona+haseeb@dragnettech.com');
  await page.getByPlaceholder('Enter your password').click();
  await page.getByPlaceholder('Enter your password').fill('Panda@2024');
  await page.getByRole('button', { name: 'LOG IN' }).click();
  await page.goto('https://beta-app.sigparser.com/Account/App/#/Default');
  await page.goto('https://beta-app.sigparser.com/Account/App/#/Dashboard');
  await page.getByRole('link', { name: 'Contacts', exact: true }).click();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('cell', { name: 'Email Address' }).getByPlaceholder('Search...').click();
  await page.getByRole('cell', { name: 'Email Address' }).getByPlaceholder('Search...').fill('mark.e@qweui.com');
  await page.locator('#body div').filter({ hasText: 'ValidApprovedIgnorePrivateOtherCoworkerFull NameCompany NameEmail AddressJob' }).nth(2).click();
  await expect(page.locator('#body div').filter({ hasText: 'ValidApprovedIgnorePrivateOtherCoworkerFull NameCompany NameEmail AddressJob' }).nth(2)).toBeVisible();
  await page.getByRole('button', { name: 'Settings ' }).click();
  await page.getByText('Updates').click();
  await page.getByRole('link', { name: 'Contact Update Tracking' }).click();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('cell', { name: 'Contact Email Address' }).getByPlaceholder('Search...').fill('mark.e@qweui.com)');
  await page.getByRole('cell', { name: 'Contact Email Address' }).getByPlaceholder('Search...').click();
  await page.getByRole('cell', { name: 'Contact Email Address mark.e@' }).getByPlaceholder('Search...').fill('mark.e@qweui.com');
  await expect(page.getByText('Mark Ronnin').first()).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Mark Ronnin' }).first()).toBeVisible();
  await page.locator('#body div').filter({ hasText: 'Date ImportedPrevious Last' }).nth(2).click();
  await page.getByRole('cell', { name: 'Updated' }).first().click();
  await page.getByRole('button', { name: '' }).click();
  await expect(page.getByRole('cell', { name: 'Updated' }).first()).toBeVisible();
  await page.getByText('Updated').first().click();
  await page.getByRole('button', { name: '' }).click();
  await expect(page.getByRole('cell', { name: '90' })).toBeVisible();
  await page.getByRole('cell', { name: '90' }).click();
  await page.getByRole('link', { name: 'Contact Update Tracking' }).click();
});