import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://beta-app.sigparser.com/');
  await page.getByRole('button', { name: 'Envelope Login with Email' }).click();
  await page.getByPlaceholder('Enter your email address').click();
  await page.getByPlaceholder('Enter your email address').fill('est+stafona+haseeb@dragnettech.com');
  await page.getByPlaceholder('Enter your email address').click();
  await page.getByPlaceholder('Enter your email address').click();
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').press('ArrowLeft');
  await page.getByPlaceholder('Enter your email address').fill('test+stafona+haseeb@dragnettech.com');
  await page.getByPlaceholder('Enter your password').click();
  await page.getByPlaceholder('Enter your password').fill('Panda@2024');
  await page.getByRole('button', { name: 'LOG IN' }).click();
  await page.goto('https://beta-app.sigparser.com/Account/App/#/Default');
  await page.goto('https://beta-app.sigparser.com/Account/App/#/Dashboard');
  await expect(page.getByRole('link', { name: 'Contacts', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Companies', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Settings ' }).click();
  await page.getByText('Updates').click();
  await expect(page.getByRole('link', { name: 'Contact Update Tracking' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Company Update Tracking' })).toBeVisible();
});