export const CommonLocators = {
    dashboardLinkLocator: 'Dashboard',
    mailBoxedLinkLocator: 'Mailboxes',
    contactsLinkLocator: 'Contacts',
    companiesLinkLocator: 'Companies',
    coworkersLinkLocator: 'Coworkers',
    connectorsLinkLocator: 'Connectors',
    settingButtonLocator: 'Settings',
    importButtonLocator: 'Import',
    importFromFileHeadingLocator: 'Import from File',
    ChooseFileTextBoxLocator: 'input[name="customerCSV"]',
    nextButtonLocator: 'Next',
    mapDataFieldLocators: 'Map data fields',
    mappingFirstdropdownLocator: '#dropdown0',
    mappingSeconddropdownLocator: '#dropdown1',
    statusQueuedNameLocator: 'StatusQueued',
    statusFinishedNameLocator: 'StatusFinished',
    importFileLocator: 'Import File',
    searchButtonLocator: 'Search',
    mappingthirddropdownLocator: '#dropdown2',
    mappingfourthdropdownLocator: '#dropdown3',
    updatesButtonLocator: 'Updates',
    domainTagFileLocator: 'CSVtest_Name',
    showAdvancedSettingsTextLocator: 'Show Advanced Settings',
    dateLocator: 'input[type="date"]',
    defaultSourceScoreDropDownLocator: '//div[@class="c-dropdown"]//select[1]',
    modalFileDetailsButtonLocator: 'Details',
    allContactUpdatesLocator: '//span[text()="All Contact Updates"]',
    allRecordAndColumns: '//div[text()="All Records & Columns"]',
    allValidCompaniesLocator: '//span[text()="All Valid Companies"]',
    allValidContactsLocator: '//span[text()="All Valid Contacts"]',
    clickingOnColumns: '//div[contains(@class,"c-container --space-between")]//span[1]',
    //Contact Custom Fields
    addFieldLocator: '//button[contains(@class,"c-btn --inverse")]',
    fieldFormHeadingLocator: 'Add Field',
    deleteLocator: 'Delete',
    plusButtonLocator: '(//button[contains(@class,"c-btn --inverse")])[1]',
    saveLocator: 'Save',
    fieldNamePlaceholder: 'Field Name',
    descriptionPlaceholder: 'Description',
    createFieldLocator: 'Create Field',
    columnTitleLocator: 'Columns',
    customFieldLocator: 'Custom Fields',
    testContactTextLinkLocator: '//b[text()="Test Contact Text"]',
    testContactTextColumnLocator: '(//div[@title="Test Contact Text : Click to Sort"]//div)[1]',
    recordTypeLocator: 'Object',
    pencilLocator: '(//i[contains(@class,"fa fa-pencil")])[3]',
    dataTypeLocator: 'Data TypeTextText',





};
