import { Page } from 'playwright';
import * as fs from 'fs';
import { CommonLocators } from '../../locators/CommonLocators';
import { CommonSteps } from '../CommonSteps';
import { MergedRecordsLocators } from '../../locators/36-MergedRecords/MergedRecords';
import { CoworkerLocator } from '../../locators/30-CSV-Imports/CoworkersLocators';

export class MergedRecords extends CommonSteps {
  constructor(page: Page) {
    super(page);
  }

  async verifyCowrokerMerge() {
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'raj');
    await this.waitForTime(1000);
    await this.waitForLocator('(//input[@type="checkbox"])[2]')
    await this.clickOnLocator('(//input[@type="checkbox"])[2]')
    await this.waitForLocator('(//input[@type="checkbox"])[3]')
    await this.clickOnLocator('(//input[@type="checkbox"])[3]')
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.clickOnLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.waitForLocator('//tr[td[@title="raj@vcfparser.com"]]//input[@type="radio"]');
    await this.clickOnLocator('//tr[td[@title="raj@vcfparser.com"]]//input[@type="radio"]');
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'raj.gupta@vcfparser.com');
    await this.waitForTime(2000);
    await this.checkLocatorAbsence('(//span[@title="raj.gupta@vcfparser.com"])[1]');
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'raj@vcfparser.com');
    await this.waitForTime(2000);
    await this.waitForLocator('//a[normalize-space(text())="Raj Gupta"]');
    await this.clickOnLocator('//a[normalize-space(text())="Raj Gupta"]');
    await this.waitForTime(5000);
    await this.waitForLocator(MergedRecordsLocators.warningLocator);
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator('//td[normalize-space(text())="raj@vcfparser.com"]');
    await this.waitForLocator('//td[normalize-space(text())="raj.gupta@vcfparser.com"]');
    await this.waitForLocator('//tr[td[normalize-space(text())="raj@vcfparser.com"]]//td[@class="c-table-static__item --xs"]//img[1]')
    await this.waitForLocator(MergedRecordsLocators.plusButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.plusButtonLocator);
    await this.waitForLocator('//input[@placeholder="Search"]');
    await this.fillingLocator('//input[@placeholder="Search"]', 'elon');
    await this.waitForLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.waitForTime(3000);
    await this.checkLocatorAbsence('(//table[@letxpath="letxpathtable"]//tr)[2]')
    await this.waitForLocator(MergedRecordsLocators.searchForCoworkerCloseButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.searchForCoworkerCloseButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.waitForLocator(MergedRecordsLocators.modalCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.modalCloseLocator);
    await this.waitForLocator('//a[normalize-space(text())="Raj Gupta"]');
    await this.clickOnLocator('//a[normalize-space(text())="Raj Gupta"]');
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator(MergedRecordsLocators.plusButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.plusButtonLocator);
    await this.waitForLocator('//input[@placeholder="Search"]');
    await this.fillingLocator('//input[@placeholder="Search"]', 'mohamed');
    await this.waitForLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLocator('(//input[@type="checkbox"])[3]');
    await this.clickOnLocator('(//input[@type="checkbox"])[3]');
    await this.waitForLocator('(//input[@type="checkbox"])[4]');
    await this.clickOnLocator('(//input[@type="checkbox"])[4]');
    await this.waitForLocator('(//input[@type="checkbox"])[5]');
    await this.clickOnLocator('(//input[@type="checkbox"])[5]');
    await this.waitForButton(MergedRecordsLocators.addSelectedButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.addSelectedButtonLocator);
    await this.waitForTime(1000);
    await this.waitForLocator('//tr[td[normalize-space(text())="mohamed.el-masri@vcfparser.com"]]//input[@name="mergeRadio"]');
    await this.clickOnLocator('//tr[td[normalize-space(text())="mohamed.el-masri@vcfparser.com"]]//input[@name="mergeRadio"]');
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'mohamed.el-masri@vcfparser.com');
    await this.waitForTime(3000);
    await this.waitForLocator('//a[normalize-space(text())="Mohamed El-Masri"]');
    await this.clickOnLocator('//a[normalize-space(text())="Mohamed El-Masri"]');
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator('//tr[td[normalize-space(text())="mohamed.el-masri@vcfparser.com"]]//td[@class="c-table-static__item --xs"]//img[1]');
    await this.waitForLocator(MergedRecordsLocators.pencilIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.pencilIconLocator);
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'raj');
    await this.waitForTime(2000);
    await this.waitForLocator('(//span[@title="raj.gupta@vcfparser.com"])[1]');
    await this.waitForLocator('(//span[@title="raj@vcfparser.com"])[1]');
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'mohamed');
    await this.waitForTime(2000);
    await this.waitForLocator('(//span[@title="mohamed.el-masri@vcfparser.com"])[1]');
    await this.waitForLocator('(//span[@title="mohamed@vcfparser.com"])[1]');
    await this.waitForLocator('(//span[@title="mohamed.elmasri@vcfparser.com"])[1]');
  }

  async verifyContactsMerge() {
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'elon');
    await this.waitForTime(1000);
    await this.waitForLocator('(//input[@type="checkbox"])[2]')
    await this.clickOnLocator('(//input[@type="checkbox"])[2]')
    await this.waitForLocator('(//input[@type="checkbox"])[3]')
    await this.clickOnLocator('(//input[@type="checkbox"])[3]')
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.clickOnLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.waitForLocator('//tr[td[@title="elon@x.com"]]//input[@type="radio"]');
    await this.clickOnLocator('//tr[td[@title="elon@x.com"]]//input[@type="radio"]');
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'elon');
    await this.waitForTime(2000);
    await this.checkLocatorAbsence('(//span[@title="elon.musk@tesla.com"])[1]');
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'elon@x.com');
    await this.waitForTime(2000);
    await this.waitForLocator('//a[normalize-space(text())="Elon Musk"]');
    await this.clickOnLocator('//a[normalize-space(text())="Elon Musk"]');
    await this.waitForTime(3000);
    await this.waitForLocator(MergedRecordsLocators.warningLocator);
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator('//td[normalize-space(text())="elon.musk@tesla.com"]');
    await this.waitForLocator('//td[normalize-space(text())="elon@x.com"]');
    await this.waitForLocator('//tr[td[normalize-space(text())="elon@x.com"]]//td[@class="c-table-static__item --xs"]//img[1]')
    await this.waitForTime(2000);
    await this.waitForLocator(MergedRecordsLocators.plusButtonContactLocator);
    await this.clickOnLocator(MergedRecordsLocators.plusButtonContactLocator);
    await this.waitForLocator('//input[@placeholder="Search"]');
    await this.fillingLocator('//input[@placeholder="Search"]', 'elon@x.com');
    await this.waitForLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.waitForTime(3000);
    await this.checkLocatorAbsence('(//table[@letxpath="letxpathtable"]//tr)[2]')
    await this.waitForLocator(MergedRecordsLocators.searchForCoworkerCloseButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.searchForCoworkerCloseButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.waitForLocator(MergedRecordsLocators.modalCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.modalCloseLocator);
    await this.waitForLocator('//a[normalize-space(text())="Elon Musk"]');
    await this.clickOnLocator('//a[normalize-space(text())="Elon Musk"]');
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator(MergedRecordsLocators.plusButtonContactLocator);
    await this.clickOnLocator(MergedRecordsLocators.plusButtonContactLocator);
    await this.waitForLocator('//input[@placeholder="Search"]');
    await this.fillingLocator('//input[@placeholder="Search"]', 'elon@twitter.com');
    await this.waitForLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.waitForLocator('(//input[@type="checkbox"])[3]');
    await this.clickOnLocator('(//input[@type="checkbox"])[3]');
    await this.waitForButton(MergedRecordsLocators.addSelectedButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.addSelectedButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLocator('//tr[td[normalize-space(text())="elon.musk@tesla.com"]]//input[@name="mergeRadio"]');
    await this.clickOnLocator('//tr[td[normalize-space(text())="elon.musk@tesla.com"]]//input[@name="mergeRadio"]');
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'elon.musk@tesla.com');
    await this.waitForTime(3000);
    await this.waitForLocator('//a[normalize-space(text())="Elon Musk"]');
    await this.clickOnLocator('//a[normalize-space(text())="Elon Musk"]');
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator('//tr[td[normalize-space(text())="elon.musk@tesla.com"]]//td[@class="c-table-static__item --xs"]//img[1]');
    await this.waitForLocator(MergedRecordsLocators.pencilIconContactLocator);
    await this.clickOnLocator(MergedRecordsLocators.pencilIconContactLocator);
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'elon');
    await this.waitForTime(2000);
    await this.waitForLocator('(//span[@title="elon.musk@tesla.com"])[1]');
    await this.waitForLocator('(//span[@title="elon@twitter.com"])[1]');
    await this.waitForLocator('(//span[@title="elon@x.com"])[1]');
  }

  async verifyCompaniessMerge() {
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForLocator('//tr[contains(td/span[@title], "x.com")]//input[@type="checkbox"]')
    await this.clickOnLocator('//tr[contains(td/span[@title], "x.com")]//input[@type="checkbox"]')
    await this.waitForLocator('//tr[contains(td/span[@title], "twitter.com")]//input[@type="checkbox"]')
    await this.clickOnLocator('//tr[contains(td/span[@title], "twitter.com")]//input[@type="checkbox"]')
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.clickOnLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.waitForLocator('//tr[td[@title="x.com"]]//input[@type="radio"]');
    await this.clickOnLocator('//tr[td[@title="x.com"]]//input[@type="radio"]');
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator, 'twitter.com');
    await this.waitForTime(2000);
    await this.checkLocatorAbsence('(//span[@title="twitter.com"])[1]');
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator, 'x.com');
    await this.waitForTime(2000);
    await this.waitForLocator('//a[normalize-space(text())="x"]');
    await this.clickOnLocator('//a[normalize-space(text())="x"]');
    await this.waitForTime(3000);
    await this.waitForLocator(MergedRecordsLocators.warningLocator);
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator('//td[normalize-space(text())="twitter.com"]');
    await this.waitForLocator('//td[normalize-space(text())="x.com"]');
    await this.waitForLocator('//tr[td[normalize-space(text())="x.com"]]//td[@class="c-table-static__item --xs"]//img[1]')
    await this.waitForTime(2000);
    await this.waitForLocator(MergedRecordsLocators.plusButtonContactLocator);
    await this.clickOnLocator(MergedRecordsLocators.plusButtonContactLocator);
    await this.waitForLocator('//input[@placeholder="Search"]');
    await this.fillingLocator('//input[@placeholder="Search"]', 'x.com');
    await this.waitForLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.waitForTime(3000);
    await this.checkLocatorAbsence('(//table[@letxpath="letxpathtable"]//tr)[2]')
    await this.waitForLocator(MergedRecordsLocators.searchForCoworkerCloseButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.searchForCoworkerCloseButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.waitForLocator(MergedRecordsLocators.modalCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.modalCloseLocator);
    await this.waitForLocator('//a[normalize-space(text())="x"]');
    await this.clickOnLocator('//a[normalize-space(text())="x"]');
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator(MergedRecordsLocators.plusButtonContactLocator);
    await this.clickOnLocator(MergedRecordsLocators.plusButtonContactLocator);
    await this.waitForLocator('//input[@placeholder="Search"]');
    await this.fillingLocator('//input[@placeholder="Search"]', 'tesla.com');
    await this.waitForLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.clickOnLocator(MergedRecordsLocators.SearchButtonLocator);
    await this.waitForLocator('(//input[@type="checkbox"])[3]');
    await this.clickOnLocator('(//input[@type="checkbox"])[3]');
    await this.waitForButton(MergedRecordsLocators.addSelectedButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.addSelectedButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLocator('//tr[td[normalize-space(text())="tesla.com"]]//input[@name="mergeRadio"]');
    await this.clickOnLocator('//tr[td[normalize-space(text())="tesla.com"]]//input[@name="mergeRadio"]');
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator, 'tesla.com');
    await this.waitForTime(3000);
    await this.waitForLocator('//a[normalize-space(text())="Tesla"]');
    await this.clickOnLocator('//a[normalize-space(text())="Tesla"]');
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator('//tr[td[normalize-space(text())="tesla.com"]]//td[@class="c-table-static__item --xs"]//img[1]');
    await this.waitForLocator(MergedRecordsLocators.pencilIconCompaniesLocator);
    await this.clickOnLocator(MergedRecordsLocators.pencilIconCompaniesLocator);
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator, 'x.com');
    await this.waitForTime(2000);
    await this.waitForLocator('(//span[@title="x.com"])[1]');
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator, 'twitter.com');
    await this.waitForTime(2000);
    await this.waitForLocator('(//span[@title="twitter.com"])[1]');
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator, 'tesla.com');
    await this.waitForTime(2000);
    await this.waitForLocator('(//span[@title="tesla.com"])[1]');
  }

  async verifyContactsAndCompaniesMerge() {
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'elon');
    await this.waitForTime(1000);
    await this.waitForLocator('(//input[@type="checkbox"])[2]')
    await this.clickOnLocator('(//input[@type="checkbox"])[2]')
    await this.waitForLocator('(//input[@type="checkbox"])[3]')
    await this.clickOnLocator('(//input[@type="checkbox"])[3]')
    await this.waitForLocator('(//input[@type="checkbox"])[4]')
    await this.clickOnLocator('(//input[@type="checkbox"])[4]')
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.clickOnLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.waitForLocator('//tr[td[@title="elon.musk@tesla.com"]]//input[@type="radio"]');
    await this.clickOnLocator('//tr[td[@title="elon.musk@tesla.com"]]//input[@type="radio"]');
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForLocator('//tr[contains(td/span[@title], "x.com")]//input[@type="checkbox"]')
    await this.clickOnLocator('//tr[contains(td/span[@title], "x.com")]//input[@type="checkbox"]')
    await this.waitForLocator('//tr[contains(td/span[@title], "twitter.com")]//input[@type="checkbox"]')
    await this.clickOnLocator('//tr[contains(td/span[@title], "twitter.com")]//input[@type="checkbox"]')
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.clickOnLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.waitForLocator('//tr[td[@title="x.com"]]//input[@type="radio"]');
    await this.clickOnLocator('//tr[td[@title="x.com"]]//input[@type="radio"]');
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'elon.musk@tesla.com');
    await this.waitForTime(1000);
    await this.waitForLocator('//a[normalize-space(text())="Tesla"]');
    await this.clickOnLocator('//a[normalize-space(text())="Tesla"]');
    await this.waitForLocator('//p[normalize-space(text())="tesla.com"]');
    await this.waitForLocator(MergedRecordsLocators.modalCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.modalCloseLocator);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'elon.musk@tesla.com');
    await this.waitForTime(1000);
    await this.waitForLocator('//a[normalize-space(text())="Elon Musk"]');
    await this.clickOnLocator('//a[normalize-space(text())="Elon Musk"]');
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator('//tr[td[normalize-space(text())="elon.musk@tesla.com"]]//td[@class="c-table-static__item --xs"]//img[1]');
    await this.waitForLocator('(//div[contains(@class,"__text-lg-bold u-m-t-5")]//i)[1]');
    await this.clickOnLocator('(//div[contains(@class,"__text-lg-bold u-m-t-5")]//i)[1]');
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForTime(1000);
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'elon');
    await this.waitForTime(1000);
    await this.waitForLocator('//span[normalize-space(text())="elon.musk@tesla.com"]');
    await this.waitForLocator('//span[normalize-space(text())="elon@x.com"]');
    await this.waitForLocator('//span[normalize-space(text())="elon@twitter.com"]');
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator, 'x.com');
    await this.waitForTime(3000);
    await this.waitForLocator('//a[normalize-space(text())="x"]');
    await this.clickOnLocator('//a[normalize-space(text())="x"]');
    await this.waitForTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.clickOnTextStrict(MergedRecordsLocators.detailsButtonInModalLocator);
    await this.waitForLocator('(//div[contains(@class,"__text-lg-bold u-m-t-5")]//i)[1]');
    await this.clickOnLocator('(//div[contains(@class,"__text-lg-bold u-m-t-5")]//i)[1]');
    await this.waitForLocator(MergedRecordsLocators.trashIconLocator);
    await this.clickOnLocator(MergedRecordsLocators.trashIconLocator);
    await this.waitForButton(MergedRecordsLocators.saveButtonLocator);
    await this.clickOnButton(MergedRecordsLocators.saveButtonLocator);
    await this.waitForTime(3000);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator, 'x.com');
    await this.waitForTime(2000);
    await this.waitForLocator('(//span[@title="x.com"])[1]');
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.companiesEmailAddressLocator, 'twitter.com');
    await this.waitForTime(2000);
    await this.waitForLocator('(//span[@title="twitter.com"])[1]');

  }

  async verifyGridSelectionForContactsPage() {
    await this.waitForLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.contactsLinkLocator);
    await this.waitForTime(3000);
    await this.waitForLocator(MergedRecordsLocators.selectAllLocator);
    await this.clickOnLocator(MergedRecordsLocators.selectAllLocator);
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.disabledMergeRecordsButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.modalCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.modalCloseLocator);
    await this.waitForLocator(MergedRecordsLocators.selectAllLocator);
    await this.clickOnLocator(MergedRecordsLocators.selectAllLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitingForEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator);
    await this.fillingEmailDomainPlaceholder(CoworkerLocator.emailAddressLocator, 'elon');
    await this.waitForTime(2000);
    await this.waitForLocator(MergedRecordsLocators.selectAllLocator);
    await this.clickOnLocator(MergedRecordsLocators.selectAllLocator);
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.clickOnLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.waitForLocator('//td[normalize-space(text())="elon.musk@tesla.com"]');
    await this.waitForLocator('//td[normalize-space(text())="elon@x.com"]');
    await this.waitForLocator('//td[normalize-space(text())="elon@twitter.com"]');
    await this.waitForLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.waitForLocator(MergedRecordsLocators.modalCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.modalCloseLocator);
    await this.waitForTime(3000);
    // await this.waitForLocator(MergedRecordsLocators.activeSelectAllLocator);
    await this.waitForLocator(MergedRecordsLocators.selectAllLocator);
    await this.clickOnLocator(MergedRecordsLocators.selectAllLocator);
    await this.waitForLocator('(//input[@type="checkbox"])[2]')
    await this.clickOnLocator('(//input[@type="checkbox"])[2]')
    await this.waitForLocator('(//input[@type="checkbox"])[3]')
    await this.clickOnLocator('(//input[@type="checkbox"])[3]')
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.clickOnLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.waitForLocator('//td[normalize-space(text())="elon.musk@tesla.com"]');
    await this.waitForLocator('//td[normalize-space(text())="elon@x.com"]');
    await this.waitForLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.waitForLocator(MergedRecordsLocators.modalCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.modalCloseLocator);
  }

  async verifyGridSelectionForCompaniesPage() {
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForTime(3000);
    await this.waitForLocator(MergedRecordsLocators.selectAllLocator);
    await this.clickOnLocator(MergedRecordsLocators.selectAllLocator);
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.disabledMergeRecordsButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.modalCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.modalCloseLocator);
    await this.waitForLocator(MergedRecordsLocators.selectAllLocator);
    await this.clickOnLocator(MergedRecordsLocators.selectAllLocator);
    await this.waitForLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.coworkersLinkLocator);
    await this.waitForLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.clickOnLinkButtonstrict(CommonLocators.companiesLinkLocator);
    await this.waitForButton(CommonLocators.searchButtonLocator);
    await this.clickOnButton(CommonLocators.searchButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.companyNameLoator);
    await this.fillingLocator(MergedRecordsLocators.companyNameLoator, 'te');
    await this.waitForTime(2000);
    await this.waitForLocator(MergedRecordsLocators.selectAllLocator);
    await this.clickOnLocator(MergedRecordsLocators.selectAllLocator);
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.clickOnLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.waitForLocator('//td[normalize-space(text())="techinnovate.com"]');
    await this.waitForLocator('//td[normalize-space(text())="tesla.com"]');
    await this.waitForLocator('//td[normalize-space(text())="twitter.com"]');
    await this.waitForLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.emailAddressCloseLocator);
    await this.waitForLocator(MergedRecordsLocators.modalCloseLocator);
    await this.clickOnLocator(MergedRecordsLocators.modalCloseLocator);
    await this.waitForTime(3000);
    // await this.waitForLocator(MergedRecordsLocators.activeSelectAllLocator);
    await this.waitForLocator(MergedRecordsLocators.selectAllLocator);
    await this.clickOnLocator(MergedRecordsLocators.selectAllLocator);
    await this.waitForLocator('(//input[@type="checkbox"])[2]')
    await this.clickOnLocator('(//input[@type="checkbox"])[2]')
    await this.waitForLocator('(//input[@type="checkbox"])[3]')
    await this.clickOnLocator('(//input[@type="checkbox"])[3]')
    await this.waitForButton(CoworkerLocator.updateButtonLocator);
    await this.clickOnButton(CoworkerLocator.updateButtonLocator);
    await this.waitForLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.clickOnLocator(MergedRecordsLocators.selectMergeRecordsButton);
    await this.waitForLocator('//td[normalize-space(text())="techinnovate.com"]');
    await this.waitForLocator('//td[normalize-space(text())="tesla.com"]');
    
  }

};