export const MergedRecordsLocators = {
    selectMergeRecordsButton: '(//button[contains(@class,"c-btn --secondary")])[2]',
    saveButtonLocator: 'Save',
    warningLocator: '(//header[@class="u-d-flex u-m-b-2"]//i)[2]',
    detailsButtonInModalLocator: 'Details',
    plusButtonLocator: '//i[contains(@class,"fa fa-plus")]',
    plusButtonContactLocator: '(//i[contains(@class,"fa fa-plus")])[2]',
    SearchButtonLocator: '//button[@type="submit"]',
    searchForCoworkerCloseButtonLocator: '(//button[@class="c-modal__exit"]//i)[3]',
    emailAddressCloseLocator: '(//i[contains(@class,"c-modal__exit-icon fa")])[2]',
    modalCloseLocator: '//i[contains(@class,"c-modal__exit-icon fa")]',
    addSelectedButtonLocator: 'Add Selected',
    pencilIconLocator: '(//i[contains(@class,"fa fa-pencil")])[3]',
    pencilIconContactLocator: '(//i[contains(@class,"fa fa-pencil")])[4]',
    pencilIconCompaniesLocator: '(//i[contains(@class,"fa fa-pencil")])[4]',
    trashIconLocator: '(//i[contains(@class,"c-btn --sm")])[1]',
    selectAllLocator: '(//input[@type="checkbox"])[1]',
    disabledMergeRecordsButtonLocator: '//section[contains(@class, "c-box") and contains(@class, "c-container") and contains(@class, "u-m-b-2")]   //button[contains(@class, "c-btn") and contains(@class, "--secondary") and @disabled]   //following-sibling::aside//p[text()="Cannot merge more than 10 records at a time."]',
    activeSelectAllLocator: '//td[contains(@class, "c-table-dynamic__item") and contains(@class, "--active")]',
    companyNameLoator: '(//input[@placeholder="Search..."])[1]',
};